scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['production-ready-app:8080']
  - job_name: 'spring-boot-app-b'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-b:8089']