
server.port: 8082

spring:
  application:
    name: production-ready-homework
  datasource:
    url: jdbc:h2:mem:mydatabase
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa: 
    show-sql: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      access: UNRESTRICTED
  metrics:
    tags:
      enabled: true     
  tracing:
    enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
  pattern:
    correlation:  "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false

